baseURL = "https://www.villadetara.com"
title = "Villa de Tara"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
newContentEditor = "code"

[Permalinks]
   posts = "/:year/:month/:contentbasename/"

[module]
  [[module.imports]]
    path = 'github.com/526avijitgupta/gokarna'

[params]
  mainSections = ["posts", "reviews"]
  accentColor = "#0d5eaf"
  description = "Kefalas, Crete"
  avatarURL = "/images/villadetara.png"
  avatarAltText = "Villa de Tara"
  avatarSize = "size-xl"
  metaKeywords = ["blog", "gokarna", "hugo"]
  togglePreviousAndNextButtons = "true"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='pen-tool'></span>"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    name = "Reviews"
    pre = "<span data-feather='thumbs-up'></span>"
    url = "/reviews/"
    weight = 30

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 40

  [[menu.main]]
    name = "Weather"
    pre = "<span data-feather='sun'></span>"
    url = "/weather/"
    weight = 60

  [[menu.main]]
    name = "About"
    pre = "<span data-feather='info'></span>"
    url = "/about/"
    weight = 70

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

[security]

  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^code$', '^git$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
