baseURL = "https://villadetara.com"
title = "Villa de Tara"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  mainSections = ["posts", "reviews"]
  themeMode = "dark"
  accentColor = "#0d5eaf"
  description = "Kefalas, Crete"
  avatarURL = "/images/pool-view.jpeg"
  AvatarAltText = "avatar"
  avatarSize = "size-xl"
  metaKeywords = ["blog", "gokarna", "hugo"]
  togglePreviousAndNextButtons = "true"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 30

  [[menu.main]]
    name = "Reviews"
    pre = "<span data-feather='thumbs-up'></span>"
    url = "/reviews/"
    weight = 40

    [[menu.main]]
    name = "Location"
    pre = "<span data-feather='globe'></span>"
    url = "/location/"
    weight = 50

  [[menu.main]]
    name = "Weather"
    pre = "<span data-feather='sun'></span>"
    url = "/weather/"
    weight = 60

  [[menu.main]]
    name = "About"
    pre = "<span data-feather='info'></span>"
    url = "/about/"
    weight = 70

[Deployment]

  [[Deployment.targets]]
    name = "AWS S3"
    URL = "s3://villadetara.com?region=eu-west-2"
    cloudFrontDistributionID = "E33G0WVXUM35IK"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false
