name: Build and Deploy villadetara.com

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::845066828582:role/villadetaraGitHubActionsRole
          role-session-name: villadetara
          aws-region: eu-west-2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.114.1'

      - name: Build website
        run: hugo --minify --verbose

      - name: Deploy to S3
        run: hugo deploy --maxDeletes -1 --invalidateCDN --verbose
