name: Deploy test.villadetara.com to Synology NAS

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        HUGO_VERSION: ${{ vars.HUGO_VERSION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'  # Ensures theme submodules are pulled

    - name: Install Hugo
      
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        tar -xzf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        sudo mv hugo /usr/local/bin/

    - name: Build Hugo Site
      run: hugo --minify --baseURL https://test.villadetara.com

    - name: Deploy to Synology NAS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_TARGET_DIR: "/volume1/web/mysite"
      run: |
        echo "$SSH_PRIVATE_KEY" > id_ed25519 && chmod 600 id_ed25519
        export RSYNC_RSH="ssh -p $SSH_PORT -i id_rsa"
        tar -czf site.tar.gz -C public .
        scp -o StrictHostKeyChecking=no -P $SSH_PORT -O site.tar.gz $SSH_USER@$SSH_HOST:/volume1/homes/$SSH_USER/site.tar.gz
        ssh -o StrictHostKeyChecking=no -p $SSH_PORT -i id_rsa $SSH_USER@$SSH_HOST "sudo tar -xzf \
            /volume1/homes/$SSH_USER/site.tar.gz -C $SSH_TARGET_DIR"